node('master'){
    stage('Build Software'){
        dir('AntExample'){
            withEnv(["ANT_HOME=C:\\opt\\ant", "JAVA_HOME=C:\\Progra~2\\Java\\jdk1.8.0_111"]){
                "${ANT_HOME}\\bin\\ant"
            }
        }
    }
}