node('master'){
    stage('Docker'){
        println "hello, world!"
    }

    stage('Grab Artifact'){
        copyArtifact()
    }

    stage('Tomcat Docker Image'){
        def warMap = [:]
        warMap = [antwar: 'AntExample.war', ]
        println warMap.get('antwar')
        
    }
}

def copyArtifact(){
    step([$class: 'CopyArtifact', fingerprintArtifacts: true, parameters: '*.war', projectName: 'multi/master', selector: [$class: 'StatusBuildSelector', stable: false], target: 'output'])

}