node('master'){
    stage('Docker'){
        println "hello, world!"
    }

    stage('Grab Artifact'){
        copy()
    }
}

def copy(){
    step([$class: 'CopyArtifact', filter: 'output/*.war', fingerprintArtifacts: true, projectName: 'multi/master', selector: [$class: 'StatusBuildSelector', stable: false], target: 'output'])

}