node('master'){
    stage('test'){
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], gitTool: 'jgit', submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'b7a9e21ffc0d6874b83e9a9d7d507644', url: 'https://github.com/netjargon/jenkins.git']]]) 
        
    }
    stage('Android build'){
        println 'Building the docker container'
        
    }

   stage('Build Dynamic Method'){
       def dynamic = Class.statik("top."execute()"")
       dynamik.get("text")
   }

   stage('Environment Testing'){
        sh "env > env.txt"
        for (String i : readFile('env.txt').split("\r?\n")) {
            println i
            }
        }
  
            }